name: Prettier Check

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    prettier-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Run Prettier check
              run: npx prettier --check .
