name: Prettier Check

on:
    push:
        branches:
            - main

jobs:
    prettier-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1

            - name: Install Node.js
              uses: actions/setup-node@v4.0.2

            - name: Install dependencies
              run: npm install

            - name: Run Prettier check
              run: npx prettier --check .
